### ISSUE TITLE
phyloscanner_analyse_trees.R problem

### ISSUE THREAD

**Issue by KF-DR** [BDI-pathogens/phyloscanner#54]
Hi,

I have been running into the same problem with both my own data set and the example dataset provided. For the example dataset my code is identical to that provided:

~/phyloscanner/phyloscanner_analyse_trees.R RAxMLfiles/RAxML_bestTree.InWindow_ MyOutput s,20 --outgroupName C.BW.00.00BW07621.AF443088 --multifurcationThreshold g 

with the output:

Random number seed is 102134702
Initialising...
Error in initialise.phyloscanner(tree.file.directory, tree.file.regex,  :
  object 'alignment.file.directory' not found
Calls: phyloscanner.analyse.trees -> initialise.phyloscanner
Execution halted

Any ideas?
Thanks,
Megan

**Comment by mdhall272** [comment]
Hi Megan,

If you mean the example dataset in ExampleOutputData_FromMakeTrees, then I cannot replicate this - are you definitely using the most up-to-date version?

Thanks, Matthew

**Comment by KF-DR** [comment]
Hi Matthew, this was from using the dataset produced by running phyloscanner_make_trees.py on the dataset from ExampleInputData and InfoAndInputs. The version on the server I'm using was last updated July 2018, so it might not be the most up-to-date.

Thanks,
Megan

**Comment by mdhall272** [comment]
Hi Megan,

That would need an update - either talk to the server people or download and install the current version from GitHub yourself?

Thanks, Matthew

**Comment by vtsyvina** [comment]
I have the same issue. I have up to date version. I just try to follow the example. I downloaded the tool for this repo. I ran commands from InstallationNotesForAnalysingTrees.sh to install R libraries.

But on a step when I run the command:
```
Rscript phyloscanner_analyse_trees.R RAxMLfiles/RAxML_bestTree. MyOutput s,12.5 --outgroupName C.BW.00.00BW07621.AF443088 --multifurcationThreshold g
```

I get the following output:
```
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘phyloscannerR’
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘sna’
Random number seed is 122882747
Error in phyloscanner.analyse.trees(tree.directory, tree.file.regex, reconstruction.mode,  :
  could not find function "phyloscanner.analyse.trees"
Execution halted
```

Not sure what to do here and how to install this phyloscannerR package. I don't see any other instructions on how to set up the tool in docs

**Comment by scotthjj** [comment]
Hi,
I have a issue. I have up to date version. I just try to follow the example. I installed VirtualBox on my computer and ran Ubuntu 16.04.3.

But on a step when I run the command:
~/phyloscanner/phyloscanner_make_trees.py InputFileList.csv --auto-window-params 300,-700,1000,8300 --alignment-of-other-refs ~/phyloscanner/InfoAndInputs/2refs_HXB2_C.BW.fasta --pairwise-align-to B.FR.83.HXB2_LAI_IIIB_BRU.K03455 

I get the following output:
Skipping to the next window.
Now extracting and processing reads in window 8000-8299
Running RAxML on the processed & aligned reads in window 8000-8299
Problem making the ML tree with RAxML in window 8000-8299. It returned an exit code of -4, printed this to stdout:

and printed this to stderr:

Skipping to the next window.
Info: phyloscanner_make_trees.py has processed all windows but has not produced any trees, either because you told it not to, or because of a lack of reads, or because of non-fatal errors. Check earlier warning/error messages.

I don't know what went wrong and what to do next. I would like to know how to solve this problem.

**Comment by ChrisHIV** [comment]
Hi @scotthjj, I've created a separate issue for you, because it's a different problem with the code despite considering the same data as other people in this thread. Please reply here https://github.com/BDI-pathogens/phyloscanner/issues/71
