### ISSUE TITLE
Issue with CalculateTreeSizeInGenomeWindows.py

### ISSUE THREAD

**Issue by BT896** [BDI-pathogens/phyloscanner#63]
Hi,

I'm trying to include branch length normalisation in analysis of trees to refine distance thresholds. I've been trying to use CalculateTreeSizeInGenomeWindows.py with reference fasta sequences as input but keeping getting the same error during FindAndCheckCode('CalculateMedianPatristicDistance.R'). At first I assumed it was the path but the main analysis has been running without issue. All phyloscanner scripts are up-to-date.

Input: 
tools/CalculateTreeSizeInGenomeWindows.py references.fas USA_U44402 \ 1 80 normalisation -I 1

Traceback (most recent call last):
  File "/software/phyloscanner-v1.8.0/tools/CalculateTreeSizeInGenomeWindows.py", line 102, in <module>
    TreeSizeCode = pf.FindAndCheckCode('CalculateMedianPatristicDistance.R')
TypeError: FindAndCheckCode() takes exactly 2 arguments (1 given)

I'm not sure what additional argument it's looking for and would appreciate any help.

Thanks

**Comment by ChrisHIV** [comment]
Hi there, are you super sure your code is up-to-date? In the current version of the `CalculateTreeSizeInGenomeWindows.py` script, which you can see at https://github.com/BDI-pathogens/phyloscanner/blob/master/tools/CalculateTreeSizeInGenomeWindows.py and compare with your own, the `FindAndCheckCode()` function appears twice (neither at line 102 as in your error message) with both occurrences having 2 arguments rather than 1. Using this version of the code works fine for me.

**Comment by ChrisHIV** [comment]
Apologies: you have 1.8.0 I see, which is the latest version tag, but we've made some small tweaks within that tag without yet creating a new tag. We'll do that soon (some separate changes are in progress), but in the mean time your problem should be fixed by updating the code.

**Comment by BT896** [comment]
Hi Chris, I've downloaded the up-to-date script and seems to working well! Thanks for your help
