### ISSUE TITLE
Bam file has more than one references given

### ISSUE THREAD

**Issue by simeonhebrew** [BDI-pathogens/phyloscanner#65]
Hello.
Running the EstimateReadcountperwindow.py python script but the resulting error was that the first bam file had more than one references given and it just expected one.
Any assistance will be highly appreciated.
-Simeon Hebrew.

**Comment by ChrisHIV** [comment]
Hi Simon, all of the python/bioinformatic part of phyloscanner is designed & structured around the idea that each file of mapped reads has only one reference, because we consider it in sliding windows (the diagram on the homepage hopefully conveys the idea). Are you analysing sequence data from an organism with a fragmented genome / multiple chromosomes? If so, you will need to create a separate bam file for each disconnected part of the genome.

**Comment by simeonhebrew** [comment]
Yeah I think so, the datasets are Trypanosomal samples (Trypanosoma congolense) that were mapped against an assembled reference genome. 
What would creating separate bam files look like? Mapping against each chromosome?
Thanks.
