### ISSUE TITLE
About Phyloscanner for with-in host

### ISSUE THREAD

**Issue by manisenthils** [BDI-pathogens/phyloscanner#75]
Hello Developers,

This is Mani, working on HIV-AIDS. Since, the past two months I have been trying to do analysis in Phyloscanner. Now I have generated sample output using example input data, after some troubleshooting and referring to the issues raised by other people on this GitHub page . As per my Knowledge those analysis were between- host with more than one patient, correct me if I am wrong. I want to analyze within-host evolution of the virus using a Individual patient sample(NGS data). I searched for instructions to do the same. but couldn't find any. Is that same process for within and between - host?  Kindly guide how I can do analysis !

thanks,
Manisenthil

**Comment by mdhall272** [comment]
Hi Manisenthil,

When you say you want to analyze within-host evolution, what kind of analysis do you have in mind? What questions do you want to answer? The tree building, first half of phyloscanner will certainly work and give you a set of windowed phylogenies, but the second is really designed to look at transmission.

Thanks, Matthew

**Comment by manisenthils** [comment]
Matthew , thanks for the response. we're looking at multiple variants of the virus within the same host and we're trying to understand, by a phylogenetic tree which of these variants is the ancestor.

thanks,
Manisenthil.

**Comment by mdhall272** [comment]
We can't tell you with phyloscanner which _virus_ is the ancestor because phyloscanner doesn't do haplotype reconstruction - there is no algorithm included to try to make a full-genome sequence for any individual virus. We instead just build phylogenies of the reads in each window.

If that limitation is not a problem, then just build the trees and have a look at them with whatever utility you please. Ignore the R script.

**Comment by manisenthils** [comment]
Okay Matthew, Thanks for your clarification on my issue.

Thanks,
Manisenthil
